/**
 * Pokemon Ceezr
 * The Ceezr pokemon API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PokemonCeezr);
  }
}(this, function(expect, PokemonCeezr) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PokemonCeezr.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('appControllerGetHello', function() {
      it('should call appControllerGetHello successfully', function(done) {
        //uncomment below and update the code to test appControllerGetHello
        //instance.appControllerGetHello(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pokemonControllerCreate', function() {
      it('should call pokemonControllerCreate successfully', function(done) {
        //uncomment below and update the code to test pokemonControllerCreate
        //instance.pokemonControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pokemonControllerFindAll', function() {
      it('should call pokemonControllerFindAll successfully', function(done) {
        //uncomment below and update the code to test pokemonControllerFindAll
        //instance.pokemonControllerFindAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pokemonControllerFindOne', function() {
      it('should call pokemonControllerFindOne successfully', function(done) {
        //uncomment below and update the code to test pokemonControllerFindOne
        //instance.pokemonControllerFindOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pokemonControllerRemove', function() {
      it('should call pokemonControllerRemove successfully', function(done) {
        //uncomment below and update the code to test pokemonControllerRemove
        //instance.pokemonControllerRemove(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pokemonControllerUpdate', function() {
      it('should call pokemonControllerUpdate successfully', function(done) {
        //uncomment below and update the code to test pokemonControllerUpdate
        //instance.pokemonControllerUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
