/**
 * Pokemon Ceezr
 * The Ceezr pokemon API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatePokemonDto model module.
 * @module model/CreatePokemonDto
 * @version 1.0
 */
class CreatePokemonDto {
    /**
     * Constructs a new <code>CreatePokemonDto</code>.
     * @alias module:model/CreatePokemonDto
     * @param name {String} 
     * @param type1 {String} 
     * @param type2 {String} 
     * @param total {Number} 
     * @param hP {Number} 
     * @param attack {Number} 
     * @param defense {Number} 
     * @param spAtk {Number} 
     * @param spDef {Number} 
     * @param speed {Number} 
     * @param generation {Number} 
     * @param legendary {Boolean} 
     */
    constructor(name, type1, type2, total, hP, attack, defense, spAtk, spDef, speed, generation, legendary) { 
        
        CreatePokemonDto.initialize(this, name, type1, type2, total, hP, attack, defense, spAtk, spDef, speed, generation, legendary);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, type1, type2, total, hP, attack, defense, spAtk, spDef, speed, generation, legendary) { 
        obj['name'] = name;
        obj['type_1'] = type1;
        obj['type_2'] = type2;
        obj['total'] = total;
        obj['hP'] = hP;
        obj['attack'] = attack;
        obj['defense'] = defense;
        obj['sp_Atk'] = spAtk;
        obj['sp_Def'] = spDef;
        obj['speed'] = speed;
        obj['generation'] = generation;
        obj['legendary'] = legendary;
    }

    /**
     * Constructs a <code>CreatePokemonDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePokemonDto} obj Optional instance to populate.
     * @return {module:model/CreatePokemonDto} The populated <code>CreatePokemonDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePokemonDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type_1')) {
                obj['type_1'] = ApiClient.convertToType(data['type_1'], 'String');
            }
            if (data.hasOwnProperty('type_2')) {
                obj['type_2'] = ApiClient.convertToType(data['type_2'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('hP')) {
                obj['hP'] = ApiClient.convertToType(data['hP'], 'Number');
            }
            if (data.hasOwnProperty('attack')) {
                obj['attack'] = ApiClient.convertToType(data['attack'], 'Number');
            }
            if (data.hasOwnProperty('defense')) {
                obj['defense'] = ApiClient.convertToType(data['defense'], 'Number');
            }
            if (data.hasOwnProperty('sp_Atk')) {
                obj['sp_Atk'] = ApiClient.convertToType(data['sp_Atk'], 'Number');
            }
            if (data.hasOwnProperty('sp_Def')) {
                obj['sp_Def'] = ApiClient.convertToType(data['sp_Def'], 'Number');
            }
            if (data.hasOwnProperty('speed')) {
                obj['speed'] = ApiClient.convertToType(data['speed'], 'Number');
            }
            if (data.hasOwnProperty('generation')) {
                obj['generation'] = ApiClient.convertToType(data['generation'], 'Number');
            }
            if (data.hasOwnProperty('legendary')) {
                obj['legendary'] = ApiClient.convertToType(data['legendary'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreatePokemonDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreatePokemonDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreatePokemonDto.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type_1'] && !(typeof data['type_1'] === 'string' || data['type_1'] instanceof String)) {
            throw new Error("Expected the field `type_1` to be a primitive type in the JSON string but got " + data['type_1']);
        }
        // ensure the json data is a string
        if (data['type_2'] && !(typeof data['type_2'] === 'string' || data['type_2'] instanceof String)) {
            throw new Error("Expected the field `type_2` to be a primitive type in the JSON string but got " + data['type_2']);
        }

        return true;
    }


}

CreatePokemonDto.RequiredProperties = ["name", "type_1", "type_2", "total", "hP", "attack", "defense", "sp_Atk", "sp_Def", "speed", "generation", "legendary"];

/**
 * @member {String} name
 */
CreatePokemonDto.prototype['name'] = undefined;

/**
 * @member {String} type_1
 */
CreatePokemonDto.prototype['type_1'] = undefined;

/**
 * @member {String} type_2
 */
CreatePokemonDto.prototype['type_2'] = undefined;

/**
 * @member {Number} total
 */
CreatePokemonDto.prototype['total'] = undefined;

/**
 * @member {Number} hP
 */
CreatePokemonDto.prototype['hP'] = undefined;

/**
 * @member {Number} attack
 */
CreatePokemonDto.prototype['attack'] = undefined;

/**
 * @member {Number} defense
 */
CreatePokemonDto.prototype['defense'] = undefined;

/**
 * @member {Number} sp_Atk
 */
CreatePokemonDto.prototype['sp_Atk'] = undefined;

/**
 * @member {Number} sp_Def
 */
CreatePokemonDto.prototype['sp_Def'] = undefined;

/**
 * @member {Number} speed
 */
CreatePokemonDto.prototype['speed'] = undefined;

/**
 * @member {Number} generation
 */
CreatePokemonDto.prototype['generation'] = undefined;

/**
 * @member {Boolean} legendary
 */
CreatePokemonDto.prototype['legendary'] = undefined;






export default CreatePokemonDto;

